ConnectionStringApplication1/Models/Categories.cs
using System.Diagnostics.CodeAnalysis;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
namespace ConnectionStringApplication1.Models;
[SuppressMessage("ReSharper", "InconsistentNaming")]
public class Categories
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int CategoryID { get; set; }

    /// <summary>
    /// Name of a category
    /// </summary>
    public string CategoryName { get; set; }

    /// <summary>
    /// Description of category
    /// </summary>
    public string Description { get; set; }

  
}

ConnectionStringApplication1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ConnectionStringApplication1.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

ConnectionStringApplication1/Pages/Index.cshtml.cs
using ConnectionStringApplication1.Classes;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Options;
using Serilog;
using System;
using ConnectionStringApplication1.Models;

#pragma warning disable CS8618

namespace ConnectionStringApplication1.Pages;
public class IndexModel : PageModel
{
    private CancellationTokenSource _cancellationTokenSource;
    public string Message { get; set; }
    public IOptions<ConnectionOptions> Options { get; }

    [BindProperty]
    public bool UseBadConnection { get; set; }

    public IndexModel(IOptions<ConnectionOptions> options)
    {
        Options = options;
        Message = "Response goes here";
        UseBadConnection = true;
    }
    
    public void OnGet()
    {
        Log.Information("Connection {P1}", Options.Value.NorthWindConnection);
        Log.Information("Connection {P1}", Options.Value.NorthWindConnectionBad);
        Log.Information("Timeout {P1}", Options.Value.TimeoutSeconds);
    }
    public async Task OnPostTestConnection()
    {
        _cancellationTokenSource = new CancellationTokenSource(
            TimeSpan.FromSeconds(Options.Value.TimeoutSeconds));


        (bool result, Exception exception) = await OpenConnection(_cancellationTokenSource.Token);

        Message = result ? 
            $"<span class=\"text-success fw-bold\">Connected successfully</span>" : 
            $"Failed with: <strong>{exception.Message}</strong>";
        
    }

    public async Task<(bool, Exception exception)> OpenConnection(CancellationToken ct)
    {
        string connectionString = UseBadConnection ? 
            Options.Value.NorthWindConnectionBad : 
            Options.Value.NorthWindConnection;

        try
        {
            await using var cn = new SqlConnection(connectionString);
            await cn.OpenAsync(ct);
            var list = cn.Query<Categories>(
                """
                SELECT CategoryID,CategoryName
                FROM dbo.Categories
                """).ToList();

            Log.Information("--------------------------");
            foreach (var cat in list)
            {
                Log.Information("Id {P1} Name {P2}", cat.CategoryID, cat.CategoryName);
            }
            Log.Information("--------------------------\n");

            return (true,null)!;
        }
        catch (TaskCanceledException tce)
        {
            return (false, tce);
        }
        catch (Exception ex)
        {
            return (false, ex);
        }
    }
}

ConnectionStringApplication1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="alert alert-danger" role="alert">
    <h1 class="fs-5 text-center">Connection timeout</h1>
</div>

<div class="d-flex align-items-center justify-content-center">


    <form id="main" method="post" class="shadow w-75">

        <div>

            <button id="submitButton" type="submit" class="btn btn-danger w-100 mb-2"  asp-page-handler="TestConnection">
                Execute
                <span id="spin" class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
            </button>
            <div class="form-check ms-1">
                <input asp-for="UseBadConnection" type="checkbox" class="form-check-input" />
                <label asp-for="UseBadConnection">Bad connection</label>
            </div>

            <div class="alert alert-danger" role="alert">
                @Html.Raw(Model.Message)
            </div>

        </div>

    </form>

</div>

<script>

    document.getElementById("submitButton").addEventListener("click",
        function () {
            let spinner = document.getElementById('spin');
            spinner.classList.remove('d-none');
        });
</script>